# Generated by Django 4.0.6 on 2022-08-02 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='beds',
            field=models.IntegerField(choices=[(1, 'one'), (2, 'two')]),
        ),
    ]
