# Generated by Django 4.0.6 on 2022-08-03 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_category_beds'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default='room'),
            preserve_default=False,
        ),
    ]
