# Generated by Django 4.0.6 on 2022-08-03 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_category_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='categories',
            field=models.CharField(choices=[('BUSINESS', 'BUSINESS'), ('ECONOMIC', 'ECONOMIC'), ('LOW', 'LOW')], max_length=10),
        ),
    ]
